application: buddhaspace-cbs
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.php

#- url: /write\.php
#  script: write.php
#
#- url: /read\.php
#  script: read.php
